### ISSUE TITLE
(kitty) Broken package

### ISSUE THREAD

**Issue by surlypants** [chocolatey-community/chocolatey-coreteampackages#1308] opened 2019-08-05 12:48 UTC
via:
https://chocolatey.org/packages/kitty

kitty.nupkg needs to be updated to reflect the changes at

https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/kitty/legal/VERIFICATION.txt

an alternative approach would be to have:
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/kitty/update.ps1

fetch VERIFICATION.txt from github, rather than baking it in to the nuget pkg.

**Comment by AdmiringWorm** [comment] 2019-08-05 16:06
I am already aware of the problems with the kitty package, and am looking into getting it updated right now.

I am also updating the `update.ps1` file to download the files from github, as well as creating the VERIFICATION.txt file during update (instead of blindly relying on the links specified in it).

**Comment by Moredread** [comment] 2019-08-05 16:15
@AdmiringWorm thanks. :) I just was looking into it, but am not that familiar with Chocolatey anymore. I guess PR #1310  can be closed in that case.

**Comment by AdmiringWorm** [comment] 2019-08-05 16:20
@Moredread yes unfortunately it will be closed (I actually just closed it right now), after adding a comment of course 😺

**Comment by AdmiringWorm** [comment] 2019-08-05 16:23
Just putting some finishing touches on the package, and need to test that it works as intended.

After the verification the changes will be pushed to this repository and a forced update will be triggered.

**Comment by AdmiringWorm** [comment] 2019-08-05 16:34
It seem it will take a little longer than what I expected.
Forgot that I didn't have the chocolatey test environment on this computer, so I need to install that first.

I will post here when a forced update have been triggered. (Although the issue will automatically be closed when the commit triggering the update is submitted).

**Comment by AdmiringWorm** [comment] 2019-08-05 17:05
A forced update have been queued on appveyor, and a forced update should be pushed shortly.

There will be a few hours until it is available on chocolatey.org though.

**Closed** 2019-08-05 17:05 UTC
Labels: 2 - Working, Bug

**Comment by kinafu** [comment] 2019-08-07 13:45
The package does not seem to be updated yet in the chocolatey repo.
