### ISSUE TITLE
(python2) Latest (2.7.15) python2 is installing 32-bit on 64-bit systems 

### ISSUE THREAD

**Issue by steveames** [chocolatey-community/chocolatey-coreteampackages#1254] opened 2019-04-02 15:17 UTC
Whenever I attempt to choco install python2 2.7.16 I'm getting the 32-bit version. Installing 2.7.15 results in the 64-bit version. Unsure what changed. In both cases I'm installing from puppet. This happens consistently. The OS is Windows 10 1809 64-bit.

## Expected Behavior

It is expected on a 64-bit system that it would install the 64-bit version of the package. And until this realease that was true.

## Current Behavior

Whenever I attempt to choco install python2 2.7.16 I'm getting the 32-bit version. Installing 2.7.15 results in the 64-bit version.

## Steps to Reproduce (for bugs)

1. spin up windows 10 Pro 1809 64-bit
2. install chocolatey
3. choco install python2
4.

## Your Environment

* Package Version used:
* Operating System and version: Windows 10 Pro 1809
* Chocolatey version: latest (2019-04-01)
* Install/uninstall gist: choco install python2

**Comment by AdmiringWorm** [comment] 2019-04-02 18:23
@steveames can you please run `choco --version` so we can confirm the version the is being used.

Would be helpful if you could also provide the full logs (located in `%CHOCOLATEYINSTALL%\logs\chocolatey.log`), or by running `choco install python2 -dv`.
Make sure to remove any secrets in the logs that you do not want to be made public.

**Comment by steveames** [comment] 2019-04-09 14:19
> I've been unable to reproduce this issue, so unless you're able to provide
> what I asked for in my previous comment, then I'm afraid there isn't much
> I can do.

thanks for trying. I've been mad busy the last week and haven't had a
chance to gather what you asked for. Will try to make time today.

**Comment by AdmiringWorm** [comment] 2019-05-04 01:08
@steveames just trying to follow up if there have been any progress on gathering what we need for this issue?

**Comment by majkinetor** [comment] 2019-06-07 11:14
Closing this as there was no feedback and the problem is not reproduced.

**Closed by majkinetor** 2019-06-07 11:14 UTC
Labels: Waiting feedback/update
