### ISSUE TITLE
(qbittorrent) Pushing v4.1.9.1 failed

### ISSUE THREAD

**Issue by ExE-Boss** [chocolatey-community/chocolatey-coreteampackages#1376] opened 2019-11-03 00:42 UTC
From https://github.com/chocolatey-community/chocolatey-coreteampackages/commit/dc506b9188c45afcf59ecc00365bbcfa42287e89 ([@⁠choco‑bot gist](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/60877521f14193cf72b627630fa138744bd705d0#ignored)):

> ## Ignored
>
> |Icon|Name|NuspecVersion|IgnoreMessage|
> |---|---|---|---|
> |<img src="https://cdn.jsdelivr.net/gh/chocolatey-community/chocolatey-coreteampackages@edba4a5849ff756e767cba86641bea97ff5721fe/icons/qbittorrent.png" width="32" height="32"/>|[qbittorrent](https://chocolatey.org/packages/qbittorrent/4.1.9.1)|[4.1.9.1](https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/qbittorrent)|AU ignored on: System.Management.Automation.RuntimeException: Chocolatey v0.10.15 Attempting to push qbittorrent.4.1.9.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository.|

**Comment by AdmiringWorm** [comment] 2019-11-03 01:34
Known issue, and the issue is already being tracked in the pinned issue #1217 .

Until the chocolatey.org issue https://github.com/chocolatey/chocolatey.org/issues/613 is fixed, this will continue to happend.

Unfortunately nothing we can do about it, and since it is a duplicate I will be closing this issue.

**Comment by AdmiringWorm** [comment] 2019-11-03 01:34
Duplicate of #1217

**Closed by AdmiringWorm** 2019-11-03 01:34 UTC
