### ISSUE TITLE
(1password) Installation failed due to change in installer

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey-community/chocolatey-coreteampackages#1186] opened 2019-01-11 09:35 UTC
## Expected Behavior
1password to be updated

## Current Behavior
Failing with an error message 
```
Installing 1PasswordSetup-7.3.657.exe...
error: Found argument '/VERYSILENT' which wasn't expected, or isn't valid in this context
USAGE:
    1PasswordSetup-7.3.657.exe [OPTIONS]
For more information try --help
ERROR:
Running ['C:\Users\[myusername]\AppData\Local\Temp\chocolatey\1password\7.3.657\1PasswordSetup-7.3.657.exe'  /VERYSILENT /NORESTART /SUPPRESSMSGBOXES /SP- /LOG="C:\Users\[myusername]\AppData\Local\Temp\chocolatey\1password.7.3.657.InnoInstall.log"] was not successful.
 Exit code was '1' See log for possible error messages..
The upgrade of 1password was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\1password\tools\chocolateyInstall.ps1'.
 See log for details.
```

## Possible Solution
Change silent installation parameters.

See [package discussion](https://chocolatey.org/packages/1password#comment-4278495253)

## Steps to Reproduce (for bugs)
1. Just install / update 1password

## Context
Update of 1password is failing, resulting that one can't install the latest version of 1password

## Your Environment
* Package Version used: 7.3.657
* Operating System and version: WS10 
* Chocolatey version: 0.10.12-beta-3-gb65f586
* Install/uninstall gist: https://gist.github.com/mkevenaar/1cbe6e74e7995d1c685e87cc07a0e908

**Comment by mkevenaar** [comment] 2019-01-13 21:09
I have tried to solve this, got updates working, but new installation fails with an permission error from installer.

**Comment by ndroftheline** [comment] 2019-01-17 18:45
same problem.

**Comment by Boxwrapper** [comment] 2019-01-21 11:53
![image](https://user-images.githubusercontent.com/17933752/51472812-dc416680-1d7a-11e9-89ad-4f81d813d3c2.png)

So apparently the installer finishes correctly if I simply run it without any arguments, also there is no gui only output in powershell ...

**Comment by AdmiringWorm** [comment] 2019-01-21 12:36
@mkevenaar are you able to verify that everything works as expected when not supplying arguments to the installer?

**Comment by mkevenaar** [comment] 2019-01-21 12:47
@AdmiringWorm I managed to get updates working, but **new install** failed.

I have pushed my changes to https://github.com/mkevenaar/chocolatey-coreteampackages/tree/fix-1password.

**Comment by AdmiringWorm** [comment] 2019-01-21 13:13
@mkevenaar do you get an error during install?
If so, what kind (or does it hang).
Could be that we need to rely on autohotkey in the latter case.

**Comment by mkevenaar** [comment] 2019-01-21 13:30
@AdmiringWorm done #1208

**Comment by aleksijohansson** [comment] 2019-03-08 23:34
Any updates on this?

**Comment by AdmiringWorm** [comment] 2019-05-04 01:15
@aleksijohansson unfortunately not, we have not been able to pinpoint the issue we have with the new installer.

**Comment by fsouza** [comment] 2019-05-04 01:28
@AdmiringWorm I was able to get this working with this change: https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1208#discussion_r268379749

I'm no longer on Windows though, it was a one-off task, so hard to confirm.

**Comment by AdmiringWorm** [comment] 2019-05-04 01:33
@mkevenaar are you able to verify that this works?
I'm unfortunately no longer in windows myself, and my vm went haywire when I tried to launch it earlier today (happens from time to time).

**Comment by mkevenaar** [comment] 2019-05-04 07:42
I hope I have some time soon to check on this @AdmiringWorm

**Comment by majkinetor** [comment] 2019-06-07 12:01
Should we fixed now, confirm.

**Comment by majkinetor** [comment] 2019-06-07 17:07
I can't work it out to force update on 1password for some reason... You will have to try it from the repo.

**Comment by AdmiringWorm** [comment] 2019-06-07 17:19
maybe uppercase stream names isn't respected by AU? or it got problems with package names starting with a number.

I also noticed it is missing the `[CmdletBinding()]` declaration. Could this be the problem?

@majkinetor ^^

**Comment by aleksijohansson** [comment] 2019-06-11 15:32
I tested this again and the same issue still persists.

**Comment by majkinetor** [comment] 2019-06-11 15:40
@aleksijohansson it isn't released on gallery, is that how you tested it ?

**Comment by aleksijohansson** [comment] 2019-06-11 15:48
@majkinetor Yes, I just normally tried to install 1password with chocolatey. I could test something else too, if you can provide instructions?

**Comment by majkinetor** [comment] 2019-06-11 16:03
Just download code cpack it and install it.

Or wait for new release. Or some admin can publish it.

/cc @gep13

**Comment by aleksijohansson** [comment] 2019-06-15 15:36
Ok, I’ll wait for the release

**Comment by pauby** [comment] 2019-08-07 15:26
New error for this:

```
Installing 1PasswordSetup-7.3.705.exe...                                                                                                       
error: Found argument '--log_path' which wasn't expected, or isn't valid in this context                                                       
USAGE:                                                                                                                                         
    1PasswordSetup-7.3.705.exe [FLAGS] [OPTIONS]                                                                                               
For more information try --help                                                                                                                
ERROR:                                                                                                                                         
Running ['C:\Users\Paul\AppData\Local\Temp\chocolatey\1password\7.3.705\1PasswordSetup-7.3.705.exe'  --log_path .] was not successful.         
 Exit code was '1' See log for possible error messages..                                                                                       
The upgrade of 1password was NOT successful.                                                                                                   
Error while running 'C:\ProgramData\chocolatey\lib\1password\tools\chocolateyInstall.ps1'.                                                     
 See log for details.                                                                                                                          
```

**Comment by majkinetor** [comment] 2019-08-07 15:35
Well, that worked when I changed the installer. Since I don't use 1password, perhaps you can give help output. 

Anyway, I am leaving this for others to take; its proprietary tool with stupid installer which I don't use. I showed how it could be done previously, perhaps something trivial could be changed such as parameter name.

Proof that it worked, i.e. that parameter existed back in time:

https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1208#discussion_r268379749

**Comment by pauby** [comment] 2019-08-07 15:38
Running the installer with `--help` gives:

```
USAGE:                                                                            
    1PasswordSetup-7.3.705.exe [FLAGS] [OPTIONS]                                  
                                                                                  
FLAGS:                                                                            
        --silent     Silent install.                                              
    -h, --help       Prints help information                                      
    -V, --version    Prints version information                                   
                                                                                  
OPTIONS:                                                                          
    -i, --install_location <INSTALL_LOCATION>    Optional: Custom install location
```

**Comment by majkinetor** [comment] 2019-08-07 15:40
OK, so they removed the parameter now. Perhaps because they added --silent so it should be even easier now and my code can be totally removed.

**Comment by pauby** [comment] 2019-08-08 08:06
I'll try and pick this one up today or tomorrow.

**Comment by pauby** [comment] 2019-08-13 10:03
I'm working on the assumption that unfortunately 1Password have not yet found an [installer they can use silently or haven't completed writing their own](https://discussions.agilebits.com/discussion/comment/509739/#Comment_509739). Either that or it's been sent to test us.

The `--silent` switch sadly doesn't install silently. What it does do it pop up a box asking if you want to install it (note that the session running Chocolatey to install it has admin rights).

![image](https://user-images.githubusercontent.com/12760779/62933206-32c2d080-bdb1-11e9-90cf-d75510d798e0.png)

Easy enough to automate that via Autohotkey which I did. It then throws up a UAC box asking you to allow it to install. I'm assuming the installer spawns another install process that doesn't inherit the admin permissions from the parent. Not sure how I get around that. Suggestions?

Finally that code @majkinetor wrote around checking the log file to see what it finishes looks like it's still needed.

**Comment by majkinetor** [comment] 2019-08-13 10:17
Try to run installer via elevated scheduled task. If UAC doesnt happen then that could do.

**Comment by pauby** [comment] 2019-08-13 12:21
Any packages that do this already that I can borrow the code from?

**Comment by mkevenaar** [comment] 2019-08-13 12:25
@pauby the Spotify package does this

**Comment by AdmiringWorm** [comment] 2019-08-13 12:55
@mkevenaar correct me if I'm wrong, but don't the spotify package run a schedule for installing spotify without admin privileges (due to requirements of the installer).

**Comment by mkevenaar** [comment] 2019-08-13 13:29
@AdmiringWorm it might be, I don’t know for sure

**Comment by majkinetor** [comment] 2019-08-13 21:56
Not the installer per se but other stuff. Take a look at virtualbox helpers and modify axcordingly. 

⁣Sent from BlueMail ​

**Comment by tescales** [comment] 2020-01-13 22:57
This remains an issue as of 1/13/2020, JFYI. Reading thru the GH issues it appears the problem is with 1password's installer, which attempts a second-order privilege elevation even when executed from an administrative prompt. I can confirm this happens on Win10-1909.

**Comment by QNimbus** [comment] 2020-01-17 09:57
I can confirm this issue. I was able to work around it by running :

`choco install 1password -f -not-silent`

**Comment by mkevenaar** [comment] 2020-07-11 10:09
This issue still exists.

**Comment by majkinetor** [comment] 2020-07-11 15:08
All issues still exists when bot announces closure. I am returning pending closure as it is obvious that nobody cares enough after more then year and a half.

**Comment by virtualex-itv** [comment] 2020-07-13 12:27
> choco install 1password -f -not-silent

I too was able to install with this command but this package deserves an update as there is a newer version available than what gets installed via chocolatey

**Comment by ropearce** [comment] 2020-07-16 13:26
This most definitely is still an issue. I use chocolatey to silently install packages (including 1Password) to my client workstations through a major name RMM. As most recent as yesterday, I was still getting the error message. If anybody wants me to test or review anything, I'm certainly happy to collaborate.

Download of 1PasswordSetup-7.3.705.exe (12.92 MB) completed.
   Hashes match.
   Installing 1password...
   Microsoft.PowerShell.Commands.WriteErrorException
   error: Found argument '--log_path' which wasn't expected, or isn't valid in this context
   USAGE:
       1PasswordSetup-7.3.705.exe [FLAGS] [OPTIONS]
   Microsoft.PowerShell.Commands.WriteErrorException
   For more information try --help
   ERROR: Running ["C:\WINDOWS\TEMP\chocolatey\1password\7.3.705\1PasswordSetup-7.3.705.exe" --log_path . ] was not successful. Exit code was '1'. See log for possible error messages.
   The install of 1password was NOT successful.
   Error while running 'C:\ProgramData\chocolatey\lib\1password\tools\chocolateyInstall.ps1'.
    See log for details.

**Comment by RedBaron2** [comment] 2020-07-16 20:58
I have a fix for the issue, but requires more testing. I'll have artifacts of the updated nupkg files on my appveyor soon for anyone that wants to test.

The installer they are using is still 'raw' and they are slowly working on only adding switches that are extremely necessary.

I'll update this post shortly with the links.

**Comment by RedBaron2** [comment] 2020-07-22 19:57
@mkevenaar @ropearce 
Thanks for the 👍 
Here is the link to the zip [file ](https://ci.appveyor.com/project/RBZ/development/build/artifacts)with my updates for the fix.
Please Test it !_! and let us know of any problems. Thanks

@majkinetor 
**FYI:** If this works well for them. There is serious work that needs to be done to the functions that are normally called for Chocolatey Installations.

**Comment by AdmiringWorm** [comment] 2020-08-04 00:22
This issue have been fixed in the repository, thanks to @mkevenaar.

A new version is being queued to be pushed to chocolatey.org.

**Closed** 2020-08-04 00:21 UTC
Labels: Up for grabs, Upstream issue
