### ISSUE TITLE
(chocolatey-core.extension) Remove-Process doesn't actually do anything

### ISSUE THREAD

**Issue by HunterZ** [chocolatey-community/chocolatey-coreteampackages#1385] opened 2019-11-16 00:25 UTC
(chocolatey-core.extension) Trying to use Remove-Process in a script or directly in PowerShell results in nothing happening and no output, even with the Verbose parameter

## Expected Behavior

Process is stopped, I think? If that's not what it's supposed to do, then the documentation is confusing.

## Current Behavior

Nothing happening and no output, even with the Verbose parameter

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

Tried all of these with no results:
```
PS C:\WINDOWS\system32> Remove-Process -NameFilter MSIAfterburner* -WithChildren True -Verbose
PS C:\WINDOWS\system32> Remove-Process -NameFilter MSIAfterburner* -WithChildren True -Verbose True
PS C:\WINDOWS\system32> Remove-Process -NameFilter "MSIAfterburner*" -WithChildren True -Verbose True
PS C:\WINDOWS\system32> Remove-Process -NameFilter "MSIAfterburner.*" -WithChildren True -Verbose True
PS C:\WINDOWS\system32> Remove-Process -NameFilter 'MSIAfterburner.*' -WithChildren True -Verbose True
```

## Context

Ultimately trying to update a package install script to kill off some processes prior to install, to avoid the need for a reboot.

## Your Environment

* Package Version used: 1.3.5
* Operating System and version: Windows 10 1909
* Chocolatey version: v0.10.15
* Install/uninstall gist: N/A

**Comment by HunterZ** [comment] 2019-11-16 00:45
Ended up implementing my own solution for now that seems to work fine. I'm new at PowerShell, so apologies if it's crude:
```
foreach($procstring in @("MSIAfterburner*","RTSS","RTSSHooksLoader*","EncoderServer*"))
{
  Write-Output "Checking whether process matching $procstring is running..."
  for($i = 1; $i -le 3; $i++)
  {
    if ($i -gt 1)
    {
      Write-Output " Try # $i : Waiting 5 seconds for process to terminate..."
      Start-Sleep -s 5
    }
    $procobj = Get-Process $procstring -ErrorAction SilentlyContinue
    if($procobj -eq $null)
    {
      Write-Output " Try # $i : SUCCESS - No process matching $procstring is running"
      break
    }
    $procid = ($procobj).id
    $procname = ($procobj).Name
    Write-Output " Try # $i : Attempting to stop active process $procname with ID $procid"
    Stop-Process -Id $procid
  }
}
```

**Comment by AdmiringWorm** [comment] 2019-11-16 00:55
I don't really know where you find the usage of `-Verbose True`. There is no such argument in the function (and it isn't automatically added since it don't use the `CmdLet` attribute.

To get the verbose output when you are calling it manually (not inside a chocolatey package) you will need to set the variable: `$VerbosePreference="Continue"`.

However, it is never meant to be called manually outside of a chocolatey package, so you should add the logic to the package first then do `choco install msiafterburner --verbose`. (you may also find the log for such an install in the `$env:ChocolateyInstall\logs\chocolatey.log`. We will need that before we can start investigating what the problem could be. (Make sure to look through that file and remove/mask secrets you don't want exposed to the public though).

> Process is stopped, I think? If that's not what it's supposed to do, then the documentation is confusing.

Indeed, it is meant to stop the process, and I know it works for at least 1 package ([`alldup`](https://chocolatey.org/packages/alldup)).

**Comment by HunterZ** [comment] 2019-11-16 05:50
Now I'm even more confused:

First, the documentation right here says that you should be able to test any of the functions from PowerShell, which conflicts with the idea they should only need to work in a Chocolatey script: https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/extensions/chocolatey-core.extension

Second, I tried it in a Chocolatey script and it didn't do anything there either.

Third, the detailed help for Remove-Process clearly states that it's a cmdlet that supports "common parameters" - including Verbose:
![image](https://user-images.githubusercontent.com/108939/68988699-45a1d280-07f0-11ea-8d1f-12110559f8fa.png)

**Comment by majkinetor** [comment] 2019-11-16 10:57
It shows:

 ```
# RegEx expression of process name, returned by Get-Process function
[string] $NameFilter
```

So you can't use wildecard syntax such as `MSIAfterburner*`, but `MSIAfterburner.*`.

**Comment by HunterZ** [comment] 2019-11-16 15:02
You can see in my original report that I tried both syntaxes. Also, the first style you mentioned absolutely works fine with both Get-Process and Stop-Process.

**Comment by majkinetor** [comment] 2019-11-18 08:50
Your solution does not gracefully shut down applications, nor does it wait for them so its not really alternative.

If you can create example that I can replicate I could offer help, otherwise, this will be closed in few days.

**Comment by AdmiringWorm** [comment] 2019-11-18 09:36
@HunterZ I did some minor testing with the lines that you posted initially, and I see the problem.

You are treating `switch` parameters as pure `bolean` value, this do not work.

Switch parameters do not accept a value (well not in that way anyhow). Remove the `True` value from `-Verbose` and `-WithChildren`.

It will work then, but you will still not get any output due to the `-Verbose` switch do not work with this function.

Even though the powershell help page mentions that `-Verbose` is supported, it is not true (this is decided by powershell help page to output, not the function itself).

> Now I'm even more confused:

> First, the documentation right here says that you should be able to test any of the functions from PowerShell, which conflicts with the idea they should only need to work in a Chocolatey script: /extensions/chocolatey-core.extension@master 

Sorry, that is my mistake. I mixed the functions in the core extension with something else.

**Comment by majkinetor** [comment] 2019-11-18 11:35
> You are treating switch parameters as pure bolean value, this do not work.

It actually works but requires special syntax: `-SwitchParam:$boolValue`

**Comment by AdmiringWorm** [comment] 2019-11-18 11:36
@majkinetor which is why I mentioned
> well not in that way anyhow

**Comment by majkinetor** [comment] 2019-11-24 12:30
Closing this due to missing feedback (no reproducible problem provided).

**Closed by majkinetor** 2019-11-24 12:30 UTC
Labels: Pending closure, Triaging, Waiting feedback/update
