### ISSUE TITLE
(CCleaner)  Add package parameter to disable "system monitoring" 

### ISSUE THREAD

**Issue by bcurran3** [chocolatey-community/chocolatey-coreteampackages#1095] opened 2018-08-15 21:31 UTC
https://chocolatey.org/packages/ccleaner

REF: https://www.ccleaner.com/docs/ccleaner/ccleaner-settings/changing-monitoring-settings-ccleaner-free

## Expected Behavior
I'd really like to have CCleaner installed without it adding itself to the Startup programs.

## Current Behavior
CCleaner adds itself into Startup after install.

## Possible Solution
REF: https://community.spiceworks.com/topic/1970818-ccleaner-how-to-turn-off-monitoring-through-a-gpo-or-reg
REF: https://forum.piriform.com/topic/52280-unable-disable-monitoring-in-5456611/
Appears toggling Computer\HKEY_CURRENT_USER\Software\Piriform\CCleaner\Monitoring to 0 will do the job or go the route of removing it from HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run

## Steps to Reproduce (for bugs)
Install CCleaner.

## Context
https://www.techspot.com/news/75826-ccleaner-updated-removed-following-outcry-over-privacy-concerns.html

## Your Environment
* Package Version used: CCleaner 5.45.6611
* Operating System and version: Win 10
* Chocolatey version: Chocolatey v0.10.11
* Install/uninstall gist: n/a

**Comment by RedBaron2** [comment] 2018-08-16 22:05
@bcurran3 @majkinetor 
I don't know how to fix this issue without using file modification of the ccleaner configuration file. I did find in my research this information.

A member of the Piriform Forums posted:
> known issue with Monitoring unable to be turned off.
v5.45 has been pulled and v5.44 should be the latest version to use.  (or earlier, available at FileHippo)

The version 5.45 has been completely removed from the [History](https://www.piriform.com/ccleaner/version-history) page. I suggest that the 5.45 version be removed from Chocolatey.

**Comment by AdmiringWorm** [comment] 2018-08-16 23:58
@RedBaron2 5.45 have been unlisted on chocolatey now.

**Comment by bcurran3** [comment] 2019-04-25 17:38
Is this still an issue with v.5.56+?

I'm not really a user...

**Comment by AdmiringWorm** [comment] 2019-05-04 00:41
@bcurran3 In that case, I will be closing this issue. If the issue is still relevant, feel free to re-open it.

**Comment by bcurran3** [comment] 2019-05-04 01:55
I do have it installed on some of my machines, just don't really use it. Pseudo default install for most friends and clients...

I think the request is still a good one.

**Comment by AdmiringWorm** [comment] 2019-05-04 01:57
Fair enough, we'll keep it open for a little while longer then.

**Closed** 2019-11-02 03:25 UTC
Labels: Enhancement, Pending closure, Up for grabs
