### ISSUE TITLE
(apache-httpd) Requires Windows 10 due to usage of Get-NetTCPConnection

### ISSUE THREAD

**Issue by EZ1cks** [chocolatey-community/chocolatey-coreteampackages#828] opened 2017-08-21 21:50 UTC
Hi, i'm on Windows 7 and i am trying to _choco install apache-httpd_ (it has been a little frustrating). First, it prompted me with:

**ERROR: The "=" operator is missing after a named argument.** – i found out it was because i was using PowerShell v2. 

Then i updated to WMF5.1, so now i have PowerShell v5, and when i try to _choco install apache-httpd_, it now prompts me with: 

**ERROR: The term 'Get-NetTCPConnection' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. The install of apache-httpd was NOT successful.** – i did some research and found out that 'Get-NetTCPConnection' does not work on Windows 7. 

Does that mean Chocolatey doesn't fully support Windows 7? Please, help!

> "it probably just means that the package does not support win7 as Get-NetTCPConnection is not a chocolatey command. that would be my first guess. maybe try requesting a workaround here:
> https://github.com/chocolatey/chocolatey-coreteampackages/issues" – **aronovgj response to my issue at gitter.im** 

* Package Version used: apache-httpd v2.4.27
* Operating System and version: Windows 7 Home Basic v6.1 (comp 7601: Service Pack 1)
* Chocolatey version: v0.10.7
* PowerShell version table: 

### Name / Value 

PSVersion / 5.1.14409.1005
PSEdition / Desktop
PSCompatibleVersions / {1.0, 2.0, 3.0, 4.0...}
BuildVersion / 10.0.14409.1005
CLRVersion / 4.0.30319.36392
WSManStackVersion / 3.0
PSRemotingProtocolVersion / 2.3
SerializationVersion / 1.1.0.1

**Comment by majkinetor** [comment] 2017-08-29 07:33
Package should be fixed as it clearly doesn't obey [1.1.12](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#1112-ensure-compatibility-with-powershell-v2), this has nothing to do with chocolatey.

**Comment by pjacobs** [comment] 2017-12-22 10:27
Is there any resolution for this issue as yet?

**Comment by majkinetor** [comment] 2017-12-22 13:33
Apparently not, due to lack of interest and contribution, otherwise issue would be closed. 

The problem is trivial to resolve for those using the package, we accept PRs.

**Comment by pjacobs** [comment] 2017-12-22 14:11
Thanks for your response.  As I am not a Windows developer with much familiarity with PowerShell, I am unaware of this trivial resolution (I'm a MacOS X developer tasked with getting my web app deployed on a Windows 2008 machine), so could you point me in the right direction and I'll make the fix and commit it.

**Comment by majkinetor** [comment] 2017-12-22 19:03
> Then i updated to WMF5.1, so now i have PowerShell v5, and when i try to choco install apache-httpd, it now prompts me with:

This is not related to PowerShell version because even if the version is the same some cmdlets do not exist on specific Windows version. TaskScheduler commands (cmdlets) or the one making the problem here is available from Windows 10 age.

One solution is to use `netstat` command to get port info.

**Comment by pjacobs** [comment] 2017-12-22 23:57
Thank you for your response.  So then I can implement my own **Get-NetTCPConnection** cmdlet using **netstat** if it does not exist on the current Windows version.

**Comment by pjacobs** [comment] 2017-12-27 09:04
As a test, I simply commented out the code for testing if the port is
already in use (where the unsupported cmdlet is used), and I found yet
another issue, which I mentioned a few months ago.  Namely, one of the
apache headers, ap_config.h, is missing from the package.  I need this
header file as I am compiling the mod_wsgi Python package to use for my
web application 

http://modwsgi.readthedocs.io/en/develop/ 

Cheers, 

PJ 

On 2017-12-23 04:03, Miodrag Milić wrote:

>> Then i updated to WMF5.1, so now i have PowerShell v5, and when i try to choco install apache-httpd, it now prompts me with:
> 
> This is not related to PowerShell version because even if the version is the same some cmdlets do not exist on specific Windows version. TaskScheduler commands (cmdlets) or the one making the problem here is available from Windows 10 age. 
> 
> One solution is to use netstat command to get port info. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/chocolatey/chocolatey-coreteampackages/issues/828#issuecomment-353657538
[2]

**Comment by AdmiringWorm** [comment] 2017-12-27 17:19
@pjacobs I'm afraid that the issue with `ap_config.h` header missing, is unfortunately out of our hands.
We just install/extract whatever is provided by the developers, creating any new files would be outside of the scope of a package.

**Comment by pjacobs** [comment] 2017-12-27 19:01
@AdmiringWorm you mean the developers of the apache-httpd package?  Ok, I will contact them directly.

**Comment by majkinetor** [comment] 2017-12-28 08:44
You could add the file on repo yourself tho, if everything else fails.

**Comment by pjacobs** [comment] 2017-12-28 22:57
Yes, that is a possibility to explore.  There is a Windows Apache distribution called Apache Lounge where I found it.

https://www.apachelounge.com/

PJ

**Comment by pjacobs** [comment] 2019-04-26 02:30
I ended up using Apache Lounge rather than the apache-httpd package, in part due to this issue, so it is no longer relevant for me, and since there hasn't been any further discussion about it since Dec 2017, I'd say the issue can be closed.

**Comment by AdmiringWorm** [comment] 2019-05-04 00:31
It is still an issue though, and although I personally don't know how to fix this, this would be a good thing to get done.

Otherwise, we would probably eventually be forced to open up this package to new maintainers that are able to implement the package the *right* way.

**Comment by AdmiringWorm** [comment] 2019-10-03 00:47
I believe this was fixed in PR #1334.
@majkinetor @RedBaron2 can you confirm?

**Closed** 2019-10-03 05:39 UTC
Labels: 0 - Backlog, Bug, Help wanted
