### ISSUE TITLE
(git) Installation fails

### ISSUE THREAD

**Issue by john3voltas** [chocolatey-community/chocolatey-coreteampackages#1382] opened 2019-11-14 10:35 UTC
## Expected Behavior

I would expect the package to install just fine

## Current Behavior

While installing the package, I get an error message and stating that installation of git.install failed.

## Possible Solution

Already tried to follow the fix in this other open issue (https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1378) but it didn't fix the issue.
Could it be related to this (https://github.com/shiftkey/chocolatey-beyondcompare/issues/29) ?
I am using Windows' own CMD as an Administrator whereas everybody seems to be using Powershell...

## Steps to Reproduce (for bugs)

Simply:
choco install git -y

## Context

This is also happening with other packages like for instance 'audacity'.

## Your Environment

* Package Version used: chocolatey-core.extension 1.3.4
* Operating System and version: Windows 7 Pro SP1 (Spanish ISO)
* Chocolatey version: Chocolatey v0.10.15
* Install/uninstall gist: https://gist.github.com/john3voltas/976cdc96a4d5f7d9b3ae0c0b5dc0969e

**Comment by psfrolov** [comment] 2019-11-14 15:41
I experience the same error with various packages (only on Windows 7 with Powershell 2.0).

**Comment by AdmiringWorm** [comment] 2019-11-14 15:41
I have verified that this is indeed a re-producible issue.

Seems to be something related to Powershell v2 compatibility (choco uses powershell when running install scripts even when you launch it through cmd).

Not yet figured out where the problem is, so still investigating that.

**Comment by majkinetor** [comment] 2019-11-14 15:57
Closing this as duplicate of #1373

**Closed by majkinetor** 2019-11-14 15:57 UTC
Labels: Bug

**Comment by RanabirChakraborty** [comment] 2023-09-19 10:01
Is there any solution of this issue?

**Comment by pauby** [comment] 2023-09-22 17:09
@RanabirChakraborty This issue is closed. Please raise a new issue.
