### ISSUE TITLE
(mp3tag) MP3tag is outdated.

### ISSUE THREAD

**Issue by Gedankenleser** [chocolatey-community/chocolatey-coreteampackages#1267] opened 2019-04-23 10:53 UTC
## Expected Behavior

- New Version should be available

## Current Behavior

- No new Version is there

## Steps to Reproduce (for bugs)

1. Visit respository (no new Version)
2. Visit Website (https://community.mp3tag.de/t/mp3tag-development-build-status/455)
3. New Version semms to be available
4.

## Your Environment

* Package Version used:
* Operating System and version: Win10Pro
* Chocolatey version:0.10.13
* Install/uninstall gist:

**Comment by AdmiringWorm** [comment] 2019-04-23 12:28
Thank you for opening this issue. I will have a look at why the new version isn't picked up by our update script as soon as I can.

**Comment by jack1142** [comment] 2019-04-24 00:01
The issue is that the update script is depending on mp3tag's author always using exactly the same format of the status message. And this one time, author forgot to put bold on Stable status and that made the script fail.
To make it more fail-proof, we could make it remove html tags from the page content first and then use regexes on that html tag stripped text. Also, I wonder if it wouldn't be better after all, to throw error if such problem appears instead of returning 'ignore'.

I see you assigned it to yourself, so I guess you'll be handling it, but I can help if you want.

**Comment by jack1142** [comment] 2019-04-24 02:25
Actually, I was checking for possible better ways and I think, getting raw single post (in Markdown) will be even better than what I proposed in last message, this url allows you to get just that, under "raw" key you have the same post we were getting before, but in format that will be easier to parse: https://community.mp3tag.de/posts/458.json

**Comment by AdmiringWorm** [comment] 2019-04-24 05:46
@jack1142 Although I've assigned myself to the issue, I have't yet started working on the issue, so feel free to work on this issue if you wish.

Using that json would definitely be a better option than what we currently have.

**Closed** 2019-04-25 09:54 UTC
Labels: Bug

**Comment by AdmiringWorm** [comment] 2019-04-25 09:55
Our updater have now been fixed for this package, and a new update build is scheduled.

Thank you @jack1142 for providing the json to grab for easier parsing.
