### ISSUE TITLE
(Chromium) Stable version of the package is outdated

### ISSUE THREAD

**Issue by thetraumer** [chocolatey-community/chocolatey-coreteampackages#1392] opened 2019-11-26 16:51 UTC
The stable version of the chromium package has not been updated since June (the prerelease version is up-to-date)

## Expected Behavior
Stable release package is up-to-date (version 78 at the time of this writing)

## Current Behavior
The stable release is version 75

## Possible Solution
Kindly please update the stable version to the latest available

**Comment by run2cmd** [comment] 2019-12-12 09:58
+1

**Comment by AdmiringWorm** [comment] 2019-12-12 10:54
If we are to update the package, that would mean that we need to look elsewhere for an more up to date version, which would be fine in most cases.

In this case though, if we were to update from a different place (like wolyss, which actually just puts links to other places), this would mean that some functionality in the current 75 version available won't be available in future versions (mostly regarding codecs for playing video, some would still be available).

**Comment by RedBaron2** [comment] 2020-03-09 03:59
@woolyss @henrypp
I am going to mention them here to see if they are even aware of the situation. I'm sure that @woolyss would know of any build from his list of links that might be comparable to the current stable version.

If no reply from either of these people in a timely manor then please proceed to close this issue.

**Comment by woolyss** [comment] 2020-03-09 16:41
Hello @AdmiringWorm @RedBaron2 

Sure you know there are always stable Chromium versions on my website. Check the github repositories of each developer or use my free APIs ;)

These following repositories focus only Chromium with Installer (executable file) for Windows OS.

## Github repositories of stable Chromium versions
- 64-bit: https://github.com/Hibbiki/chromium-win64/tags
- 32-bit: https://github.com/Hibbiki/chromium-win32/tags

## My API
With My API, there are 1 more release because Arm uses my site to share their official Chromium releases. More info at https://chromium.woolyss.com/#windows-on-arm

Also, I added the "official" development version for fun! ;)

### 64-bit
64-bit stable : 
 - (json): https://chromium.woolyss.com/api/v5/?os=win64&type=stable-sync&out=json
 - https://chromium.woolyss.com/api/v5/?os=win64&type=stable-sync

64-bit stable **Arm** : 
 - (json): https://chromium.woolyss.com/api/v5/?os=win64&type=stable-nosync-arm&out=json
 - https://chromium.woolyss.com/api/v5/?os=win64&type=stable-nosync-arm

64-bit dev: 
 - (json): https://chromium.woolyss.com/api/v5/?os=win64&type=dev-official&out=json
 - https://chromium.woolyss.com/api/v5/?os=win64&type=dev-official

### 32-bit
32-bit stable : 
 - (json): https://chromium.woolyss.com/api/v5/?os=win32&type=stable-sync&out=json
 - https://chromium.woolyss.com/api/v5/?os=win32&type=stable-sync

32-bit dev: 
 - (json): https://chromium.woolyss.com/api/v5/?os=win32&type=dev-official&out=json
 - https://chromium.woolyss.com/api/v5/?os=win32&type=dev-official

**Comment by RedBaron2** [comment] 2020-03-19 18:22
Working on this should be ready as time allows

**Comment by RedBaron2** [comment] 2020-03-21 00:37
@woolyss 
The Version 5 of your API has a bug for the dev-official feed
It reports two different version numbers for [32bit](http://chromium.woolyss.com/api/v5/?os=win32&type=dev-official&out=json) or [64bit](https://chromium.woolyss.com/api/v5/?os=win64&type=dev-official&out=json)
These version numbers are not the same for 
The Version 2  of your API reports the same version numbers for both the [32bit](https://chromium.woolyss.com/api/v2/?os=windows&bit=32&out=json) or [64bit](https://chromium.woolyss.com/api/v2/?os=windows&bit=64&out=json)

**Comment by woolyss** [comment] 2020-03-21 09:04
Hello RedBaron2,
This not a bug. This is completely normal. The official Chromium buildbot can have a good result for 64-bit version and a bad result for its 32-bit version... and vice-versa.

You can check yourself on the official Chromium repositories at
- 64-bit: https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/
- 32-bit: https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/

I made a screenshot to explain that clearer! ;)

Link: https://i.imgur.com/67Y0TLy.png
![](https://i.imgur.com/67Y0TLy.png)

**Closed** 2020-04-01 11:02 UTC
Labels: Enhancement, Outdated
