### ISSUE TITLE
(julia) Command not recognized after 'choco install julia'

### ISSUE THREAD

**Issue by andremillet** [chocolatey-community/chocolatey-coreteampackages#1304] opened 2019-07-09 16:00 UTC
this is what happens
sorry for the image, idk how to copy from power shell
![Sem título](https://user-images.githubusercontent.com/561993/60904465-7faf0680-a249-11e9-82c7-a445783eddfb.png)

**Comment by majkinetor** [comment] 2019-08-21 13:44
Does it work with refreshenv command or in new shell?

**Comment by andremillet** [comment] 2019-08-21 13:58
it worked using wls. switched to ubuntu though, so I am unable to perform
more tests

*André Millet*



Em qua, 21 de ago de 2019 às 10:44, Miodrag Milić <notifications@github.com>
escreveu:

**Comment by majkinetor** [comment] 2019-08-21 17:22
Its most probable then that refreshenv would solve your issue or shell restart

**Comment by PiotrSokol** [comment] 2019-08-24 21:48
Unfortunately `refreshenv` doesn't do anything.

**Comment by drelatgithub** [comment] 2019-09-06 15:44
I think I found the reason for this, but I might need some help and suggestions before I can start to fix this.

### Facts
1. Julia installation allows multiple versions of Julia to simultaneously exist. So when running a Julia installer of a newer version, the older version(s) will not be removed. When multiple versions are installed, multiple registry keys exist, each for a different version.
1. Currently, the shimming executable for Julia will be removed before uninstallation and before upgrading.
1. Currently, uninstallation of older versions of Julia is not performed before upgrading.
1. Function `Get-AppInstallLocation` will abort finding in registry when multiple entries are found. (As a side note, after aborting, trying to find executable in `PATH` can be one of the causes for Issue #1175)

### What's happening
1. The problem happens when upgrading Julia to a newer version.
1. Before upgrading, the original shimming executable is removed.
1. New version of Julia is installed, so an *additional* registry entry is added for Julia.
1. In script `chocolateyinstall.ps1`, function `Get-AppInstallLocation` aborts finding in registry, because in registry, multiple entries of Julia is found.
1. Script `chocolateyinstall.ps1` returns before the shimming file is created, because the install location is unclear from registry.

### Possible fixes
- Replace `Get-AppInstallLocation` with `Get-UninstallRegistryKey` and select the *last* entry (the newest one), to get the correct install location.
    Pros: Easy fix; should work for normal upgrading
    Cons: The incorrect version might be shimmed when the user decides to install an older version of Julia (the last entry might be not the one currently being installed).
- Assume registry format and replace `Get-AppInstallLocation` with `Get-UninstallRegistryKey` and match the current installed version.
    Pros: The newly created shimming will always correspond to the version currently being installed.
- Uninstall the older version before upgrading.
    Pros: Older versions are removed so the older entries can be deleted.
    Cons: Might be not applicable as @AdmiringWorm said in per Issue #1175
    > Since the uninstall script is expected to fail if there is something wrong, we can't do that.

### Other fixes that might also apply
- Remove `chocolateyuninstall.ps1` since the shimming removal is moved to `chocolateybeforemodify.ps1`, and the rest can be automatically taken care of.

**Comment by majkinetor** [comment] 2019-09-06 18:40
Assume registry format vairant is what I would go with. Maybe even assume installdir format for yet easier solution.

**Comment by majkinetor** [comment] 2019-09-14 13:55
I wont push AU fix for this as package is frequently updated so this will be usable in next release.

**Closed by majkinetor** 2019-09-14 13:55 UTC
